# Generated by Django 5.1.5 on 2025-03-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipItem',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=100)),
                ('itemDescription', models.TextField()),
                ('itemCondition', models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Damaged', 'Damaged'), ('Broken', 'Broken'), ('Repaired', 'Repaired'), ('Refurbished', 'Refurbished'), ('Faulty', 'Faulty'), ('Other', 'Other')], max_length=50)),
                ('itemStatus', models.CharField(max_length=50)),
                ('itemDetail', models.TextField()),
            ],
        ),
    ]
