# Generated by Django 5.1.5 on 2025-03-02 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Warehouse', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipPackage',
            fields=[
                ('package_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.package')),
                ('SPID', models.AutoField(primary_key=True, serialize=False)),
                ('TrackingNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('siteName', models.CharField(blank=True, max_length=100, null=True)),
                ('siteURL', models.URLField(blank=True, null=True)),
                ('packageNote', models.TextField(blank=True, null=True)),
            ],
            bases=('api.package',),
        ),
        migrations.CreateModel(
            name='WarehouseOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.order')),
                ('BFMID', models.AutoField(primary_key=True, serialize=False)),
                ('ServiceCharge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('isPalette', models.BooleanField(default=False)),
            ],
            bases=('api.order',),
        ),
        migrations.AddField(
            model_name='shipitem',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.shippackage'),
        ),
        migrations.AddField(
            model_name='shippackage',
            name='BFMID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Warehouse.warehouseorder'),
        ),
        migrations.AddField(
            model_name='shipitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Warehouse.warehouseorder'),
        ),
    ]
