# Generated by Django 5.1.5 on 2025-03-02 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.order')),
                ('SOID', models.AutoField(primary_key=True, serialize=False)),
                ('warrantyValue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('GoldenDiscount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shippingMethod', models.CharField(blank=True, max_length=50, null=True)),
                ('trackingNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SO_profile', to='api.order')),
            ],
            bases=('api.order',),
        ),
    ]
