# Generated by Django 5.1.5 on 2025-02-06 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0003_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Shipment.users')),
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_status', models.CharField(max_length=50)),
                ('agent_creation_date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
            bases=('Shipment.users',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Shipment.users')),
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ref_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='Shipment.users')),
            ],
            bases=('Shipment.users',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('orderType', models.CharField(max_length=50)),
                ('orderStatus', models.CharField(max_length=50)),
                ('coinsUsed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderDiscount', models.IntegerField()),
                ('promoCodeUsed', models.DateTimeField(auto_now_add=True)),
                ('estimated_delivery', models.DateTimeField()),
                ('delivery_date_time', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shipment.customer')),
            ],
        ),
    ]
