# Generated by Django 5.1.5 on 2025-02-07 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0007_rename_address_type_address_addresstype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Shipment.users')),
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_status', models.CharField(max_length=50)),
                ('agent_creation_date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
            bases=('Shipment.users',),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('packageID', models.AutoField(primary_key=True, serialize=False)),
                ('packageName', models.CharField(max_length=100)),
                ('packageWidth', models.FloatField()),
                ('packageLength', models.FloatField()),
                ('packageHeight', models.FloatField()),
                ('packageWeight', models.FloatField()),
                ('packageStatus', models.CharField(max_length=50)),
                ('packageDetail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=4)),
                ('expiry', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_date_time',
            new_name='deliveryDateTime',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='estimated_delivery',
            new_name='estimatedDelivery',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceID', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Shipment.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('orderHistoryID', models.AutoField(primary_key=True, serialize=False)),
                ('historyStatus', models.CharField(max_length=50)),
                ('historyCreationDateTime', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shipment.order')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('shippingID', models.AutoField(primary_key=True, serialize=False)),
                ('shippingMethod', models.CharField(max_length=50)),
                ('shippingStatus', models.CharField(max_length=50)),
                ('trackingNumber', models.CharField(max_length=100)),
                ('shippingCreationDateTime', models.DateTimeField(auto_now_add=True)),
                ('type_id', models.IntegerField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Shipment.order')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketID', models.AutoField(primary_key=True, serialize=False)),
                ('ticketType', models.CharField(max_length=50)),
                ('ticketStatus', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shipment.customer')),
                ('ticketAgent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shipment.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('commentDateTime', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shipment.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=255)),
                ('fileType', models.CharField(max_length=50)),
                ('fileSize', models.IntegerField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shipment.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionOD', models.AutoField(primary_key=True, serialize=False)),
                ('transactionType', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('transactionDateTime', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shipment.customer')),
            ],
        ),
    ]
