# Generated by Django 5.1.5 on 2025-02-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0008_agent_package_paymentmethod_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
