# Generated by Django 5.1.5 on 2025-02-07 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0012_alter_item_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shipment.users'),
        ),
    ]
