# Generated by Django 5.1.5 on 2025-02-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0013_package_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='order',
            new_name='user',
        ),
    ]
