# Generated by Django 5.1.5 on 2025-02-07 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0014_rename_order_package_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='user',
        ),
        migrations.AddField(
            model_name='package',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shipment.customer'),
        ),
    ]
