# Generated by Django 5.1.5 on 2025-02-07 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0015_remove_package_user_package_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shipment.customer'),
        ),
    ]
