# Generated by Django 5.1.5 on 2025-02-07 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0017_package_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionOD',
            new_name='transactionID',
        ),
        migrations.AddField(
            model_name='customer',
            name='ESCoins',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shipment.order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paymentMethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shipment.paymentmethod'),
        ),
    ]
