# Generated by Django 5.1.5 on 2025-02-07 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0018_alter_users_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='ticket',
        ),
        migrations.AddField(
            model_name='attachment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shipment.comment'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shipment.item'),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('referralID', models.AutoField(primary_key=True, serialize=False)),
                ('referralCode', models.CharField(max_length=50)),
                ('referralCreationDateTime', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shipment.customer')),
            ],
        ),
    ]
