# Generated by Django 5.1.5 on 2025-02-27 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('countryID', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=100)),
                ('countryISO', models.CharField(max_length=10)),
                ('countryCode', models.CharField(max_length=10)),
                ('countryCurrency', models.CharField(max_length=10)),
                ('countryLanguage', models.CharField(max_length=50)),
                ('countryCapital', models.CharField(max_length=100)),
                ('countryPopulation', models.IntegerField()),
                ('countryArea', models.FloatField()),
                ('countryContinent', models.CharField(max_length=50)),
                ('countryCurrencyCode', models.CharField(max_length=10)),
                ('countryCurrencyName', models.CharField(max_length=50)),
                ('countryCurrencySymbol', models.CharField(max_length=10)),
                ('countryCurrencyRate', models.FloatField()),
                ('countryTimezone', models.CharField(max_length=50)),
                ('countryTimezoneGMT', models.CharField(max_length=10)),
                ('countryTimezoneDST', models.CharField(max_length=10)),
                ('countryTimezoneDSTStart', models.DateTimeField()),
                ('countryTimezoneDSTEnd', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['countryName'],
            },
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_addresses', to='UserManagement.countries'),
        ),
    ]
