# Generated by Django 5.1.5 on 2025-02-07 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('commentDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceID', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_creation_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=100)),
                ('itemDescription', models.TextField()),
                ('itemType', models.CharField(max_length=50)),
                ('itemValue', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('orderType', models.CharField(max_length=50)),
                ('orderStatus', models.CharField(max_length=50)),
                ('coinsUsed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderDiscount', models.IntegerField()),
                ('promoCodeUsed', models.DateTimeField(auto_now_add=True)),
                ('estimatedDelivery', models.DateTimeField()),
                ('deliveryDateTime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('orderHistoryID', models.AutoField(primary_key=True, serialize=False)),
                ('historyStatus', models.CharField(max_length=50)),
                ('historyCreationDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('packageID', models.AutoField(primary_key=True, serialize=False)),
                ('packageName', models.CharField(max_length=100)),
                ('packageWidth', models.FloatField()),
                ('packageLength', models.FloatField()),
                ('packageHeight', models.FloatField()),
                ('packageWeight', models.FloatField()),
                ('packageStatus', models.CharField(max_length=50)),
                ('packageDetail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('shippingID', models.AutoField(primary_key=True, serialize=False)),
                ('shippingMethod', models.CharField(max_length=50)),
                ('shippingStatus', models.CharField(max_length=50)),
                ('trackingNumber', models.CharField(max_length=100)),
                ('shippingCreationDateTime', models.DateTimeField(auto_now_add=True)),
                ('type_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketID', models.AutoField(primary_key=True, serialize=False)),
                ('ticketType', models.CharField(max_length=50)),
                ('ticketStatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionID', models.AutoField(primary_key=True, serialize=False)),
                ('transactionType', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('transactionDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=255)),
                ('fileType', models.CharField(max_length=50)),
                ('fileSize', models.IntegerField()),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.comment')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.item')),
            ],
        ),
    ]
