# Generated by Django 5.1.5 on 2025-03-02 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyForMeOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.order')),
                ('BFMID', models.AutoField(primary_key=True, serialize=False)),
                ('siteName', models.CharField(max_length=100)),
                ('siteURL', models.URLField()),
                ('ServiceCharge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='BFM_profile', to='api.order')),
            ],
            bases=('api.order',),
        ),
    ]
